CLS
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT







PRINT "                                   /\"
PRINT "                                 /    \"
PRINT "                               /        \"
PRINT "                             /            \"
PRINT "                             I            I"
PRINT "                             I      U     I"
PRINT "                            /I            I\"
PRINT "                          /  I      S     I  \"
PRINT "                        /    I            I    \"
PRINT "                      /      I      A     I      \"
PRINT "                    /        I            I        \"
PRINT "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   "
PRINT "                "; ""; ""; ""; ""; ""; ""; ""; ""; ""; ""; ""; ""; ""; ""; ""
FOR I = 1 TO 25
FOR J = 1 TO 1000
NEXT J
PRINT
NEXT I
END

