CLS
SCREEN 2
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                   /\"
PRINT "                                  /  \                 "
PRINT "                                 /    \"
PRINT "                                 \    /"
PRINT "                                 /    \"
PRINT "                                /      \"
PRINT "                               /        \ "
PRINT "                              /          \"
PRINT "                             /            \      "
PRINT "                             \            /    "
PRINT "                             /            \   "
PRINT "                            /              \ "
PRINT "                           /                \"
PRINT "                          /                  \            "
PRINT "                         /                    \ "
PRINT "                         \                    /"
PRINT "                         /                    \"
PRINT "                        /                      \"
PRINT "                       /                        \"
PRINT "                      /                          \"
PRINT "                     /                            \"
PRINT "                    /                              \"
PRINT "                    |                              |"
PRINT "                   /|                              |\"
PRINT "                  / |                              | \"
PRINT "                 /  |                              |  \"
PRINT "                /   |                              |   \"
PRINT "               /    |                              |    \"
PRINT "              /     |------------------------------|     \"
PRINT "             /______|                              |______\"
PRINT "                    |                              |     "
PRINT "                     \\\\\\\\\\\\\\////////////////"
PRINT "                       \\\\\\\\\\\\//////////////"
PRINT "                        ------------------------"
PRINT "                               "; CHR$(176); CHR$(177); CHR$(178); CHR$(178); CHR$(177); CHR$(176); CHR$(178)
PRINT "                                "; CHR$(177); CHR$(178); CHR$(178); CHR$(178); CHR$(177)
PRINT "                                 "; CHR$(178); CHR$(178); CHR$(178)

FOR I = 1 TO 25
FOR J = 1 TO 1003
NEXT J
PRINT
NEXT I
CLS

